-- MySQL Script generated by MySQL Workbench
-- Wed Sep 19 13:37:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listaReyes` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `listaReyes` ;

-- -----------------------------------------------------
-- Table `listaReyes`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listaReyes`.`USUARIOS` (
  `NOMBRE_USUARIO` VARCHAR(50) NOT NULL,
  `CONTRASENA` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NOMBRE_USUARIO`),
  UNIQUE INDEX `NOMBRE_USUARIO_UNIQUE` (`NOMBRE_USUARIO` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listaReyes`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listaReyes`.`PRODUCTOS` (
  `ID` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(500) NOT NULL,
  `IMAGEN` VARCHAR(250) NOT NULL,
  `ENLACE_COMPRA` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listaReyes`.`LISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listaReyes`.`LISTAS` (
  `ID` INT NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `NOMBRE_USUARIO` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `NOMBRE_USUARIO_idx` (`NOMBRE_USUARIO` ASC),
  CONSTRAINT `NOMBRE_USUARIO`
    FOREIGN KEY (`NOMBRE_USUARIO`)
    REFERENCES `listaReyes`.`USUARIOS` (`NOMBRE_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listaReyes`.`LISTA_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listaReyes`.`LISTA_PRODUCTOS` (
  `ID_LISTA` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  `COMPRADO` INT NOT NULL,
  PRIMARY KEY (`ID_LISTA`, `ID_PRODUCTO`),
  INDEX `ID_PRODUCTO_idx` (`ID_PRODUCTO` ASC),
  CONSTRAINT `ID_LISTA`
    FOREIGN KEY (`ID_LISTA`)
    REFERENCES `listaReyes`.`LISTAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PRODUCTO`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `listaReyes`.`PRODUCTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
