-- MySQL Script generated by MySQL Workbench
-- Tue Oct  9 15:52:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `listareyes` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `listareyes` ;

-- -----------------------------------------------------
-- Table `listareyes`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listareyes`.`USUARIOS` (
  `NOMBRE_USUARIO` VARCHAR(50) NOT NULL,
  `CONTRASENA` VARCHAR(60) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NOMBRE_USUARIO`),
  UNIQUE INDEX `NOMBRE_USUARIO_UNIQUE` (`NOMBRE_USUARIO` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listareyes`.`LISTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listareyes`.`LISTAS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `EMAIL_idx` (`EMAIL` ASC),
  CONSTRAINT `EMAIL`
    FOREIGN KEY (`EMAIL`)
    REFERENCES `listareyes`.`USUARIOS` (`EMAIL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `listareyes`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `listareyes`.`PRODUCTOS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_LISTA` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(50) NOT NULL,
  `DESCRIPCION` VARCHAR(500) NOT NULL,
  `IMAGEN` VARCHAR(250) NOT NULL,
  `ENLACE_COMPRA` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `ID_LISTA_idx` (`ID_LISTA` ASC),
  CONSTRAINT `ID_LISTA`
    FOREIGN KEY (`ID_LISTA`)
    REFERENCES `listareyes`.`LISTAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
